[package]
name = "backend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]

near-sdk = "3.1.0"
near-contract-standards = "3.1.1"
chrono = "0.4"
