[package]
name = "sendNFT"
version = "0.1.0"
edition = "2018"
authors = ["Near Inc <hellp@nearapps.io>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.1"